mysite/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^hai/', views.sayHai),
    url(r'(\d+)/' ,views.detail),
    ]

mysite/blog/models.py
from django.db import models

# Create your models here.
class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hlaunch_date = models.DateTimeField()
    birthday = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.hname

class SkinInfo(models.Model):
    sname = models.CharField(max_length=20)
    scontent = models.CharField(max_length=200)
    shero = models.ForeignKey(HeroInfo)

    def __str__(self):
        return self.sname

mysite/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
# from django.template import loader
# from .models import *

def index(request):
    response = HttpResponse("hello")
    cookies = request.COOKIES
    if cookies.has_key('name'):
        response.write(cookies['name'])
    return response

mysite/blog/templates/blog/blog.html
<!--blog.html-->

mysite/blog/templates/blog/detail.html
<html>
	<head>
		<title>Detail</title>
	</head>
	<body>
		<h1>{{ hero.hname }}</h1>
		<h2>{{ hero.hgender }}, {{ hero.hlaunch_date }}</h2>
		<hr/>
		<ul>
		{% for skin in hero.skininfo_set.all %}
			<li>{{ skin.sname }}: {{ skin.scontent }}</li>
		{% endfor %}
		</ul>
	</body>
</html>

mysite/blog/templates/blog/index.html
<!--index.html-->
<html>
	<head>
		<title>index</title>
	</head>
	<body>
		<h1 style="margin-left: 20px;">Hero List</h1>
		<hr/>
		{% for hero in herolist %}
		<li style="list-style-type: none; margin-left: 20px;">
		<a href="{{ hero.id }}"> <h4>{{ hero.hname }} </h4> </a>
		</li>
		{% endfor %}
	</body>
</html>